# Generated by Django 4.0.6 on 2022-07-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=13)),
                ('content', models.TextField()),
                ('Timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
