# Generated by Django 4.0.6 on 2022-07-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=130, max_length=130),
            preserve_default=False,
        ),
    ]
