# Generated by Django 4.0.6 on 2022-07-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_post_blogcomment_post_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default=1, upload_to='static'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=1),
        ),
    ]
